import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

// Middleware to parse JSON bodies
app.use(express.json());

// 1. Serve Static Files (The React App)
// This serves the 'dist' folder generated by 'npm run build'
app.use(express.static(path.join(__dirname, 'dist')));

// 2. The Chat API Endpoint (Ported from worker.js)
app.post('/api/chat', async (req, res) => {
    try {
        const { message, businesses } = req.body;

        if (!process.env.ANTHROPIC_API_KEY) {
            throw new Error('Missing ANTHROPIC_API_KEY env var');
        }

        // Create context about businesses
        const businessContext = businesses
            .map(b => `- ${b.name} (${b.category?.name || 'Business'}): ${b.discount} - ${b.address}${b.distance ? ` - ${Math.round(b.distance * 7)} min by bike` : ''}`)
            .join('\n');

        const systemPrompt = `You are a helpful assistant for Bicycle Benefits in Madison, WI. You help cyclists find businesses that offer discounts to people who arrive by bicycle.

Here are the nearby participating businesses:
${businessContext}

Be concise and friendly. When recommending businesses, mention their discount and approximate bike time. If asked about categories, list relevant options. Keep responses brief (2-3 sentences max).`;

        // Call Claude API
        const response = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': process.env.ANTHROPIC_API_KEY,
                'anthropic-version': '2023-06-01'
            },
            body: JSON.stringify({
                // Note: Check if 'claude-haiku-4' is valid, usually it's 'claude-3-haiku-20240307'
                // I kept your teammate's model string, but if it fails, switch to 'claude-3-haiku-20240307'
                model: 'claude-3-haiku-20240307', 
                max_tokens: 300,
                system: systemPrompt,
                messages: [
                    { role: 'user', content: message }
                ]
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('Claude API error:', errorText);
            return res.status(500).json({ error: 'Claude API request failed' });
        }

        const data = await response.json();
        const assistantMessage = data.content[0].text;

        return res.json({ response: assistantMessage });

    } catch (error) {
        console.error('Chat error:', error);
        return res.status(500).json({ error: 'Failed to process chat' });
    }
});

// Handle React Routing (Redirect all other requests to index.html)
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
